version: "3"
services:
  postgres:
    image: postgres:9
    container_name: my_postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: dbadmin
      POSTGRES_PASSWORD: AdminPassword
      POSTGRES_INITDB_ARGS: --encoding=UTF8%
